language: go

before_install:
  - wget --no-clobber https://github.com/bazelbuild/bazel/releases/download/0.23.0/bazel_0.23.0-linux-x86_64.deb
  - sudo dpkg -i bazel_0.23.0-linux-x86_64.deb

install:
  - mv .bazelrc.travis .bazelrc
  
script:
  - bazel test --color=no --curses=no --show_timestamps --test_output=errors //foo/...
