language: go

before_install:
  - wget --no-clobber https://github.com/bazelbuild/bazel/releases/download/0.8.1/bazel_0.8.1-linux-x86_64.deb
  - sudo dpkg -i bazel_0.8.1-linux-x86_64.deb

install:
  - mv .bazelrc.travis .bazelrc
  
script:
  - bazel test --test_output=errors //foo/...
