"com_github_jmhodges_bazel_bugs is a place for reproducing bugs in the Bazel software ecosystem"

module(
    name = "com_github_jmhodges_bazel_bugs",
    version = "1.0.0",
    compatibility_level = 1,
)

bazel_dep(name = "rules_go", version = "0.58.3")
bazel_dep(name = "gazelle", version = "0.46.0")
