name: Keeping Go up to date
on:
  push:
    branches:
      - ensure_action
jobs:
  fresh_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ensure_action
      - run: pwd
      - run: ls -l
      - uses: jmhodges/ensure_latest_go@87c34372e39d66fe0d4f8cb11251bc6ccb67a43e
        id: ensure_go
        with:
          dockerfiles: "./Dockerfile"
      - run: echo "##[set-output name=pr_title;]update to latest Go release ${{ steps.ensure_go.outputs.go_version}}"
        id: pr_title_maker
      - name: Create pull request
        uses: peter-evans/create-pull-request@v1.5.2
        env:
          PULL_REQUEST_TITLE: ${{ steps.pr_title_maker.outputs.pr_title }}
          COMMIT_MESSAGE: ${{ steps.pr_title_maker.outputs.pr_title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
