name: Keeping Go up to date
on:
  push:
    branches:
      - ensure_action
jobs:
  fresh_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ensure_action
      - run: pwd
      - run: ls -l
      - uses: jmhodges/ensure_latest_go@23914b43f7130be6569b30641d2db038314d3cdc
        id: ensure_go
        with:
          dockerfiles: "./Dockerfile"
      - run: echo "welp steps: ${{ steps }} ensure_go ${{ steps.ensure_go }}"
      # - run: echo "##[set-output name=pr_title;]updating to latest Go release ${{ steps.ensure_go.outputs.go_version}}"
      #   id: pr_title_maker
      # - name: Create pull request
      #   uses: peter-evans/create-pull-request@v1.5.2
      #   env:
      #     PULL_REQUEST_TITLE: ${{ steps.pr_title_maker.outputs.pr_title }}
      #     COMMIT_MESSAGE: ${{ steps.pr_title_maker.outputs.pr_title }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
